spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: fantasy_admin
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
#     ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


